# Config file of ${project.name}.
# This file was originally created by version ${project.version}.

# The language file used by the plugin. Must be placed next to this file.
languageFile: translations-en.yml

# The updater. Possible values:
# AUTO_INSTALL - check for updates, install new files when possible, otherwise
#                notify the server admins
# JUST_NOTIFY - check for updates, notify the server admins
# DISABLED - don't check for updates
#
# Before installing an update, the plugin checks that
# a) the new file is compatible with your Minecraft version
# b) the file is hosted on spigotmc.org
# c) it is safe to install this file automatically. When the file is flagged
#    as needing a manual installation by the author, the file won't be
#    installed automatically
updater: AUTO_INSTALL

# All types of containers that can be protected.
# All material names can be found here:
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
protectableContainers:
- ACACIA_FENCE_GATE
- ANVIL
- BEACON
- BIRCH_FENCE_GATE
- BREWING_STAND
- BURNING_FURNACE
- CHEST
- DARK_OAK_FENCE_GATE
- DISPENSER
- DROPPER
- ENCHANTMENT_TABLE
- FENCE_GATE
- FURNACE
- HOPPER
- JUKEBOX
- JUNGLE_FENCE_GATE
- SPRUCE_FENCE_GATE
- TRAPPED_CHEST
- WORKBENCH

# When set to true, one sign protects all connected nearby blocks of the same
# type. When false, each container requires a separate sign.
# Please note that a double chest is one container, so one sign is enough to
# protect the whole chest, regardless of this setting.
connectContainers: false

# All types of doors that can be protected. These blocks must follow the data
# value format as described here:
# http://minecraft.gamepedia.com/Data_values#Door
protectableDoors:
- WOODEN_DOOR
- IRON_DOOR_BLOCK
- SPRUCE_DOOR
- BIRCH_DOOR
- JUNGLE_DOOR
- ACACIA_DOOR
- DARK_OAK_DOOR

# All types of trap doors that can be protected. These blocks must be
# be recognized by the Bukkit API as a trap door.
protectableTrapDoors:
- TRAP_DOOR
- IRON_TRAPDOOR

# The default amount of seconds a door stays open before closing automatically.
# Players can override this value by putting a [Timer:X] tag on the sign, where
# X is a number from 0 to 9.
# When using 0 or a negative value, the door will never close automatically.
# When the door was opened using redstone, the door will never close
# automatically too.
defaultDoorOpenSeconds: 0
