name: ${project.name}
version: "${project.version}"
main: nl.rutgerkok.blocklocker.impl.BlockLockerPluginImpl
author: Rutger Kok
load: startup
api-version: 1.18
softdepend: [Guilds, Factions, mcMMO, Towny]
permissions:
  blocklocker.protect:
    description: "Protect containers and doors."
    default: true
  blocklocker.bypass:
    description: "Bypass someone else's protection."
    default: op
  blocklocker.edit:
    description: "Edit someone else's protection."
    default: op
  blocklocker.reload:
    description: "Reload the plugin using /blocklocker reload."
    default: op
  blocklocker.wilderness:
    description: "Place chests in the wilderness (outside of Towny claims)"
    default: true
commands:
  blocklocker:
    description: "Administration commands for BlockLocker."
    permission: "blocklocker.reload"
    usage: "/<command> reload"
    aliases: "bl"
