name: ${project.name}
version: ${project.version}
main: nl.rutgerkok.blocklocker.impl.BlockLockerPluginImpl
author: Rutger Kok
load: startup
permissions:
  blocklocker.protect:
    description: "Protect containers and doors."
    default: true
  blocklocker.bypass:
    description: "Bypass someone else's protection."
    default: op
  blocklocker.reload:
    description: "Reload the plugin using /blocklocker reload."
    default: op
commands:
  blocklocker:
    description: "Edit a sign on your protection."
    permission: "blocklocker.protect"
    usage: "/<command> <lineNumber> <value>"
    aliases: "bl"
