name: ${project.name}
version: ${project.version}
main: nl.rutgerkok.blocklocker.impl.BlockLockerPluginImpl
author: Rutger Kok
load: startup
permissions:
  blocklocker.protect:
    description: "Allows the user to protect containers and doors."
    default: true
