name: ${project.name}
version: ${project.version}
main: nl.rutgerkok.blocklocker.impl.BlockLockerPluginImpl
author: Rutger Kok
load: startup
permissions:
  blocklocker.protect:
    description: "Allows the user to protect containers and doors."
    default: true
  blocklocker.bypass:
    description: "Allows the user to bypass someone else's protection."
    default: op
commands:
  blocklocker:
    description: "Edit a sign on your protection."
    permission: "blocklocker.protect"
    usage: "/<command> <lineNumber> <value>"
